spring:
  application:
    name: "remat-backend"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/remat_server}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# JWT ??
jwt:
  secret: ${JWT_SECRET_KEY:your-secret-key-must-be-at-least-32-characters-long-for-hs256-algorithm-security}
  access-token-validity: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000}
